### 
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "name": "Test",
    "password": "MonMotDePasseSecret123!"
}

### 
@authToken = {{login.response.body.token}}

### D1PlayTime
GET http://localhost:3000/api/stats/D1PlayTime
Content-Type: application/json
Authorization: Bearer {{authToken}}

{

}

### D2PlayTime
GET http://localhost:3000/api/stats/D2PlayTime
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    
}